Update dotfiles

diff --git a/bin/dotfiles b/bin/dotfiles
--- a/bin/dotfiles
+++ b/bin/dotfiles
@@ -1,16 +1,5 @@
 #!/bin/bash
 
-#emoji codes
-CHECK_MARK="\033[00;32m\xE2\x9C\x94\033[0m"
-X_MARK="\033[00;31m\xE2\x9C\x96\033[0m"
-PIN="\033[00;31m\xF0\x9F\x93\x8C\033[0m"
-CLOCK="\033[00;32m\xE2\x8C\x9B\033[0m"
-ARROW="\033[00;36m\xE2\x96\xB6\033[0m"
-BOOK="\033[00;31m\xF0\x9F\x93\x8B\033[0m"
-HOT="\033[00;33m\xF0\x9F\x94\xA5\033[0m"
-WARNING="\033[00;31m\xF0\x9F\x9A\xA8\033[0m"
-RIGHT_ANGLE="\033[00;32m\xE2\x88\x9F\033[0m"
-
 # color codes
 RESTORE='\033[0m'
 NC='\033[0m'
@@ -21,7 +10,7 @@ YELLOW='\033[00;33m'
 BLUE='\033[00;34m'
 PURPLE='\033[00;35m'
 CYAN='\033[00;36m'
-SEA="\033[38;5;49m"
+SEA="\\033[38;5;49m"
 LIGHTGRAY='\033[00;37m'
 LBLACK='\033[01;30m'
 LRED='\033[01;31m'
@@ -33,128 +22,238 @@ LCYAN='\033[01;36m'
 WHITE='\033[01;37m'
 OVERWRITE='\e[1A\e[K'
 
-DOTFILES_LOG="$HOME/.dotfiles.log"
+#emoji codes
+CHECK_MARK="${GREEN}\xE2\x9C\x94${NC}"
+X_MARK="${RED}\xE2\x9C\x96${NC}"
+PIN="${RED}\xF0\x9F\x93\x8C${NC}"
+CLOCK="${GREEN}\xE2\x8C\x9B${NC}"
+ARROW="${SEA}\xE2\x96\xB6${NC}"
+BOOK="${RED}\xF0\x9F\x93\x8B${NC}"
+HOT="${ORANGE}\xF0\x9F\x94\xA5${NC}"
+WARNING="${RED}\xF0\x9F\x9A\xA8${NC}"
+RIGHT_ANGLE="${GREEN}\xE2\x88\x9F${NC}"
 
+
+
+set -e
+
+# Paths
+VAULT_SECRET_FILE="$HOME/.ansible-vault/vault.secret"
+OP_INSTALLED=false
+OP_AUTHENTICATED=false
+OP_VAULT_SECRET=""
+ID=""
+DOTFILES_LOG="$HOME/.dotfiles.log"
+DOTFILES_DIR="$HOME/.dotfiles"
+SSH_DIR="$HOME/.ssh"
+IS_FIRST_RUN="$HOME/.dotfiles_run"
 # _header colorize the given argument with spacing
-function _task {
-    if [[ $TASK != "" ]]; then
-        printf "${OVERWRITE}${LGREEN} [✓]  ${LGREEN}${TASK}\n"
-    fi
-    TASK=$1
-    printf "${LBLACK} [ ]  ${TASK} \n${LRED}"
+function __task {
+  # if _task is called while a task was set, complete the previous
+  if [[ $TASK != "" ]]; then
+    printf "${OVERWRITE}${LGREEN} [✓]  ${LGREEN}${TASK}\n"
+  fi
+  # set new task title and print
+  TASK=$1
+  printf "${LBLACK} [ ]  ${TASK} \n${LRED}"
 }
 
 # _cmd performs commands with error checking
 function _cmd {
-    if ! [[ -f $DOTFILES_LOG ]]; then
-        touch $DOTFILES_LOG
-    fi
-    >$DOTFILES_LOG
-    if eval "$1" 1>/dev/null 2>$DOTFILES_LOG; then
-        return 0
-    fi
-    printf "${OVERWRITE}${LRED} [X]  ${TASK}${LRED}\n"
-    while read line; do
-        printf "      ${line}\n"
-    done <$DOTFILES_LOG
-    printf "\n"
-    rm $DOTFILES_LOG
-    exit 1
+  #create log if it doesn't exist
+  if ! [[ -f $DOTFILES_LOG ]]; then
+    touch $DOTFILES_LOG
+  fi
+  # empty conduro.log
+  > $DOTFILES_LOG
+  # hide stdout, on error we print and exit
+  if eval "$1" 1> /dev/null 2> $DOTFILES_LOG; then
+    return 0 # success
+  fi
+  # read error from log and add spacing
+  printf "${OVERWRITE}${LRED} [X]  ${TASK}${LRED}\n"
+  while read line; do
+    printf "      ${line}\n"
+  done < $DOTFILES_LOG
+  printf "\n"
+  # remove log file
+  rm $DOTFILES_LOG
+  # exit installation
+  exit 1
 }
 
-set -e
+function _clear_task {
+  TASK=""
+}
 
-CONFIG_DIR="$HOME/.config/dotfiles"
-VAULT_SECRET="$HOME/.ansible-vault/vault.secret"
-DOTFILES_DIR="$HOME/.dotfiles"
-SSH_DIR="$HOME/.ssh"
-IS_FIRST_RUN="$HOME/.dotfiles_run"
+function _task_done {
+  printf "${OVERWRITE}${LGREEN} [✓]  ${LGREEN}${TASK}\n"
+  _clear_task
+}
 
-# Install Ansible
-if ! command -v ansible &>/dev/null; then
-    _task "Installing Ansible"
-    if [[ "$(uname)" == "Darwin" ]]; then
-        _cmd "brew install ansible@8"
-    elif [[ "$(uname)" == "Linux" ]]; then
-        _cmd "sudo apt-get update"
-        _cmd "sudo apt-get install -y software-properties-common"
-        _cmd "sudo apt-add-repository -y ppa:ansible/ansible"
-        _cmd "sudo apt-get update"
-        _cmd "sudo apt-get install -y ansible"
-        _cmd "sudo apt-get install python3-argcomplete"
-        _cmd "sudo activate-global-python-argcomplete3"
+function ubuntu_setup() {
+  if ! dpkg -s ansible >/dev/null 2>&1; then
+    __task "Installing Ansible"
+    _cmd "sudo apt-get update"
+    _cmd "sudo apt-get install -y software-properties-common"
+    _cmd "sudo apt-add-repository -y ppa:ansible/ansible"
+    _cmd "sudo apt-get update"
+    _cmd "sudo apt-get install -y ansible"
+    _cmd "sudo apt-get install python3-argcomplete"
+    _cmd "sudo activate-global-python-argcomplete3"
+  fi
+  if ! dpkg -s python3 >/dev/null 2>&1; then
+    __task "Installing Python3"
+    _cmd "sudo apt-get install -y python3"
+  fi
+
+  local UBUNTU_MAJOR_VERSION=$(echo $VERSION_ID | cut -d. -f1)
+  if [ $UBUNTU_MAJOR_VERSION -le 22 ]; then
+    if ! dpkg -s python3-pip >/dev/null 2>&1; then
+      __task "Installing Python3 Pip"
+      _cmd "sudo apt-get install -y python3-pip"
     fi
-fi
-
-# Check if python3 and pip is installed
-if ! command -v python3 &>/dev/null; then
-    _task "Installing Python3"
-    if [[ "$(uname)" == "Darwin" ]]; then
-        _cmd "brew install python"
-    elif [[ "$(uname)" == "Linux" ]]; then
-        _cmd "sudo apt-get install -y python3"
+    if ! pip3 list | grep watchdog >/dev/null 2>&1; then
+      __task "Installing Python3 Watchdog"
+      _cmd "sudo apt-get install -y python3-watchdog"
     fi
-fi
+  fi
+}
 
-if ! command -v pip3 &>/dev/null; then
-    _task "Installing Python3 Pip"
-    if [[ "$(uname)" == "Darwin" ]]; then
-        _cmd "brew install python"
-        _cmd "brew install pipx"
-    elif [[ "$(uname)" == "Linux" ]]; then
-        _cmd "sudo apt-get install -y python3-pip"
-    fi
-fi
+function arch_setup() {
+  if ! [ -x "$(command -v ansible)" ]; then
+    __task "Installing Ansible"
+    _cmd "sudo pacman -Sy --noconfirm"
+    _cmd "sudo pacman -S --noconfirm ansible"
+    _cmd "sudo pacman -S --noconfirm python-argcomplete"
+    # _cmd "sudo activate-global-python-argcomplete3"
+  fi
+  if ! pacman -Q python3 >/dev/null 2>&1; then
+    __task "Installing Python3"
+    _cmd "sudo pacman -S --noconfirm python3"
+  fi
+  if ! pacman -Q python-pip >/dev/null 2>&1; then
+    __task "Installing Python3 Pip"
+    _cmd "sudo pacman -S --noconfirm python-pip"
+  fi
+  if ! pip3 list | grep watchdog >/dev/null 2>&1; then
+    __task "Installing Python3 Watchdog"
+    _cmd "sudo pacman -S --noconfirm python-watchdog"
+  fi
 
-# Check if pip module watchdog is installed
+  if ! pacman -Q openssh >/dev/null 2>&1; then
+    __task "Installing OpenSSH"
+    _cmd "sudo pacman -S --noconfirm openssh"
+  fi
 
-if [[ "$(uname)" == "Darwin" ]]; then
-    if ! pipx list | grep "watchdog" &>/dev/null; then
-        _task "Installing Python3 Watchdog"
-        _cmd "pipx install watchdog"
-    fi
+  __task "Setting Locale"
+  _cmd "sudo localectl set-locale LANG=en_US.UTF-8"
+}
+
+function macos_setup() {
+  if ! [ -x "$(command -v brew)" ]; then
+    __task "Installing Homebrew"
+    _cmd "/bin/bash -c \"$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)\""
+  fi
+  if ! [ -x "$(command -v git)" ]; then
+    __task "Installing Git"
+    _cmd "brew install git"
+  fi
+  if ! [ -x "$(command -v ansible)" ]; then
+    __task "Installing Ansible"
+    _cmd "brew install ansible"
+  fi
+  if ! [ -x "$(command -v op)" ]; then
+    __task "Installing 1Password CLI"
+    _cmd "brew install 1password@beta"
+    _cmd "brew install 1password-cli@beta"
+    __task "Setting up 1Password CLI"
+    # press any key to continue
+    read -n 1 -s -r -p "Press any key to continue"
+    echo -e "${OVERWRITE}${OVERWRITE} [✓]  ${GREEN}1Password CLI setup complete${NC}" && _clear_task
+  fi
+}
+
+update_ansible_galaxy() {
+  local os=$1
+  local os_requirements=""
+  __task "Updating Ansible Galaxy"
+  if [ -f "$DOTFILES_DIR/requirements/$os.yml" ]; then
+    __task "${OVERWRITE}Updating Ansible Galaxy with OS Config: $os"
+    os_requirements="$DOTFILES_DIR/requirements/$os.yml"
+  fi
+  _cmd "ansible-galaxy install -r $DOTFILES_DIR/requirements/common.yml $os_requirements"
+}
+
+function confirmVaultAccess() {
+  __task "Checking for 1Password CLI"
+  if ! command -v op >/dev/null 2>&1; then
+    printf "${OVERWRITE} ${RED}[X]  Checking for 1Password CLI\n"
+    printf " ${WARNING}${RED}   1Password CLI is not installed.${NC}\n"
+    exit 1
+  fi
+  local op_version
+  op_version=$(op --version)
+  __task "1Password CLI found: [$op_version] -- Authenticating..."
+  if ! _cmd "op --account my.1password.com vault list"; then exit 1; fi
+  _task_done && printf "${GREEN} [✓] Successfully authenticated with 1Password CLI! ☕\n"
+  return
+}
+
+if [ -f /etc/os-release ]; then
+  source /etc/os-release
 else
-    if ! pip3 list | grep "watchdog" &>/dev/null; then
-        _task "Installing Python3 Watchdog"
-        _cmd "python -m pip install watchdog"
-    fi
+  ID=$(uname -s | tr '[:upper:]' '[:lower:]')
 fi
 
-# Generate SSH keys
+__task "Loading Setup for detected OS: $ID"
+case $ID in
+  ubuntu)
+    ubuntu_setup
+    ;;
+  arch)
+    arch_setup
+    ;;
+  darwin)
+    macos_setup
+    ;;
+  *)
+    __task "Unsupported OS"
+    _cmd "echo 'Unsupported OS'"
+    ;;
+esac
+
+
 if ! [[ -f "$SSH_DIR/authorized_keys" ]]; then
-    _task "Generating SSH keys"
-    _cmd "mkdir -p $SSH_DIR"
-    _cmd "chmod 700 $SSH_DIR"
-    _cmd "ssh-keygen -b 4096 -t rsa -f $SSH_DIR/id_rsa -N '' -C $USER@$HOSTNAME"
-    _cmd "cat $SSH_DIR/id_rsa.pub >> $SSH_DIR/authorized_keys"
+  __task "Generating SSH keys"
+  _cmd "mkdir -p $SSH_DIR"
+  _cmd "chmod 700 $SSH_DIR"
+  _cmd "ssh-keygen -b 4096 -t rsa -f $SSH_DIR/id_rsa -N '' -C $USER@$HOSTNAME"
+  _cmd "cat $SSH_DIR/id_rsa.pub >> $SSH_DIR/authorized_keys"
 fi
 
-# Clone repository
 if ! [[ -d "$DOTFILES_DIR" ]]; then
-    _task "Cloning repository"
-    _cmd "git clone https://github.com/DR-DinoMight/dotfiles.git $DOTFILES_DIR"
+  __task "Cloning repository"
+  _cmd "git clone --quiet https://github.com/TechDufus/dotfiles.git $DOTFILES_DIR"
 else
-    _task "Updating repository"
-    _cmd "git -C $DOTFILES_DIR pull"
+  __task "Updating repository"
+  _cmd "git -C $DOTFILES_DIR pull --quiet"
 fi
 
-pushd "$DOTFILES_DIR" 2>&1 >/dev/null
-_task "Updating Galaxy"
-_cmd "ansible-galaxy install -r requirements.yml"
+pushd "$DOTFILES_DIR" 2>&1 > /dev/null
+update_ansible_galaxy $ID
 
-_task "Running playbook"
-if [[ -f $VAULT_SECRET ]]; then
-    _task "Found Vault - $VALUT_SECRET"
-    ansible-playbook --vault-password-file $VAULT_SECRET "$DOTFILES_DIR/main.yml" "$@" --ask-become-pass
-else
-    _task "No Valut  - $VALUT_SECRET"
-    ansible-playbook "$DOTFILES_DIR/main.yml" "$@" --ask-become-pass
-fi
+confirmVaultAccess
 
-popd 2>&1 >/dev/null
+rm -f $VAULT_SECRET_FILE
+ansible-playbook "$DOTFILES_DIR/main.yml" "$@"
+
+popd 2>&1 > /dev/null
 
 if ! [[ -f "$IS_FIRST_RUN" ]]; then
-    echo -e "${CHECK_MARK} ${GREEN}First run complete!${NC}"
-    echo -e "${ARROW} ${CYAN}Please reboot your computer to complete the setup.${NC}"
-    touch "$IS_FIRST_RUN"
+  echo -e "${CHECK_MARK} ${GREEN}First run complete!${NC}"
+  echo -e "${ARROW} ${CYAN}Please reboot your computer to complete the setup.${NC}"
+  touch "$IS_FIRST_RUN"
 fi
+
+# vi:ft=sh:
